INSERT INTO public.tasks (condition, answer, status) VALUES ('На ветке сидело 4 воробья и 3 снегиря. Сколько птиц сидело на ветке?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На лугу паслось 5 коров и 1 бык. Сколько животных было на лугу?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На стоянке стояло 3 машины. Вечером приехало ещё 6 машин. Сколько машин стало?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На кусте было 2 распустившиеся розы. Через 3 дня распустилось ещё 4 розы. Сколько распустившихся роз стало на кусте?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На столе стояло 4 тарелки. Мама поставила ещё 2 тарелки. Сколько тарелок стало на столе?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У подъезда росло 4 дерева. Дети посадили столько же деревьев. Сколько деревьев теперь растёт у подъезда?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Кати было 4 куклы. На день рождения девочке подарили ещё 3 куклы. Сколько кукол стало у Кати?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В маршрутном такси ехало 5 человек. На остановке вошли ещё 3 человека. Сколько пассажиров стало в маршрутном такси?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У мамы было 9 гвоздик. Потом ей подарили ещё 3 гвоздики. Сколько гвоздик стало у мамы?', '12', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Вани было 2 кассеты с мультфильмами. Ему купили ещё 4 кассеты. Сколько кассет стало у Вани?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На даче росло 4 куста смородины. Посадили ещё 6 кустов. Сколько кустов смородины теперь растёт на даче?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Светы было 5 открыток. Ей прислали ещё 4 открытки. Сколько открыток стало у Светы?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Мальчик за первую четверть прочитал 4 книги, за вторую четверть — 5 книг, а за третью столько, сколько за первую и вторую четверти вместе. Сколько книг прочитал мальчик в третьей четверти?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В букете было 2 красные розы, 5 белых роз, а розовых столько, сколько красных и белых вместе. Сколько розовых роз в букете?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В хоре поют 3 девочки, танцами занимаются 5 девочек, а в театральном кружке играют столько девочек, сколько их поёт в хоре и занимается танцами. Сколько девочек в театральном кружке?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На день рождения Маше подарили 3 куклы, 5 мишек, а воздушных шариков столько, сколько кукол и мишек вместе. Сколько воздушных шариков подарили Маше?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На опушке леса росло 4 берёзы и 3 дуба, а елей столько, сколько берёз и дубов вместе. Сколько елей росло на опушке леса?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Саша исписал за первую четверть 2 тетради, за вторую четверть — 4 тетради, а за третью четверть столько, сколько за первую и вторую четверти вместе. Сколько тетрадей исписал Саша в третей четверти?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В букете 3 колокольчика, 7 ромашек, а васильков столько, сколько колокольчиков и ромашек вместе. Сколько васильков в букете?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На стоянке стояло 4 красные машины, 5 синих, а белых машин столько, сколько красных и синих вместе. Сколько белых машин на стоянке?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Миша утром решил 1 задачу, днём — 4 задачи, а вечером столько, сколько утром и днём вместе. Сколько задач решил Миша вечером?', '5', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В русском языке 3 согласные буквы, которые обозначают всегда твёрдый звук, и 3 согласные буквы, которые обозначают всегда мягкий звук, а звонких парных согласных столько, сколько всегда твёрдых и всегда мягких вместе. Сколько в русском языке звонких парных согласных букв?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Оле 5 лет, Тане 3 года, а Юре столько лет, сколько Оле и Тане вместе. Сколько лет Юре?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В первый день Митя нарисовал 4 рисунка, во второй — столько же. Сколько всего рисунков нарисовал Митя?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Юры 3 машинки и у Максима столько же. Сколько машинок у Максима?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В одном стручке 5 горошин и в другом столько же. Сколько горошин в двух стручках?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На одной ветке 2 яблока и на другой столько же. Сколько яблок на двух ветках?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У папы 1 сестра и столько же братьев. Сколько всего братьев и сестёр у папы?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В вазе лежало 5 карамелек и столько же шоколадных конфет. Сколько всего конфет лежало в вазе?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У кошки 3 белых и столько же чёрных котят. Сколько всего котят у кошки?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На доске лежало 4 куска белого мела и столько же зелёного. Сколько всего кусков мела лежало на доске?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На столе стояло 2 блюдца и столько же чашек. Сколько посуды на столе?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В секции занимались 5 мальчиков и столько же девочек. Сколько детей занималось в секции?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На берёзе сидело 6 воробьёв. Прилетело ещё 4. Сколько воробьёв стало?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Белка устроила гнездо в дупле дуба. Днём она принесла туда 8 грибов, а вечером — 4 гриба. Сколько грибов оказалось в дупле?', '12', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На цветке сидит пчела, собирает пыльцу. К ней прилетела ещё 1 пчела. Сколько всего пчёл на цветке?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Ребята заготовили для птиц 5 кг рябины и 5 кг семян арбуза. Сколько всего килограммов семян заготовили ребята?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Вокруг Марса вращаются 2 естественных спутника, а вокруг планеты Уран — 5 спутников. Сколько всего спутников у Марса и Урана вместе?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Геологи нашли семь камней, масса которых 1 кг, 2 кг, 3 кг, 4 кг, 5 кг, 6 кг, 7 кг. Эти камни разложили в четыре рюкзака так, чтобы в каждом рюкзаке масса камней была одинакова. Как это сделали? (Напиши сколько камней в каждом рюкзаке)', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В хоре пели 4 мальчика и 6 девочек. Сколько детей всего пело в хоре?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Дети учатся в школе 4 месяца до Нового года и 5 месяцев после Нового года. Сколько всего месяцев дети учатся в школе?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На стройку привезли 5 машин песка и 3 машины цемента. Сколько всего машин приехало на стройку?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В первом конверте 5 марок, а во втором — 3 марки. Сколько всего марок в двух конвертах?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Мальчик за первую четверть исписал 6 тетрадей, за вторую четверть — 3 тетради. Сколько всего тетрадей он исписал за две четверти?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В коридоре стояло 5 стульев. Принесли ещё 3. Сколько стульев стало?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В первый день машина проехала 30 км, во второй — 10 км. Сколько километров машина проехала за два дня?', '40', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Во дворе играло 5 котят. К ним подошло ещё 3 котёнка. Сколько котят стало?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В первую четверть Аня болела 4 дня, во вторую — 6 дней. Сколько всего дней Аня болела в эти две четверти?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В автобусе ехали 7 пассажиров. На остановке вошли ещё 3 пассажира. Сколько пассажиров стало в автобусе?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В первый день около школы посадили 20 деревьев, во второй — ещё 10 деревьев. Сколько всего деревьев посадили?', '30', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В первой группе 7 мальчиков, во второй группе 3 мальчика, а в третьей столько, сколько в первой и второй вместе. Сколько мальчиков в третьей группе?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Таня засушила 4 кленовых и 5 дубовых листьев. Сколько всего листьев засушила Таня?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В первый день в магазин привезли 5 пачек книг, во второй — 4 пачки, а в третий столько, сколько в первый и второй вместе. Сколько пачек книг привезли в магазин в третий день?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Зина купила 5 тетрадей в клетку и 2 в линейку. Сколько всего тетрадей купила Зина?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('За последние три столетия исчезло 36 видов млекопитающих и 94 вида птиц. Скольких всего видов птиц и млекопитающих лишилась наша родная планета?', '130', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Возле школы росло 9 елей. Посадили ещё 4 дуба и 6 елей. Сколько всего елей стало возле школы?', '15', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Дикие гуси живут 80 лет, а собаки — 20 лет. Орёл живёт столько, сколько собака и гусь вместе взятые. Сколько лет живёт орёл?', '100', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Сейчас охота в нашей стране запрещена полностью на 18 видов зверей и 29 видов птиц. На сколько видов зверей и птиц запрещена охота?', '47', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Таня вымыла 6 тарелок, а Коля вымыл 7 тарелок. Сколько всего тарелок вымыли дети?', '13', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В первой квартире живут 3 человека, во второй — 4 человека, а в третьей столько, сколько в первой и второй вместе. Сколько человек живёт в третьей квартире?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Глаз насекомого имеет мозаичное (фасеточное) строение. Он состоит из множества глазков. У мухи их 4 тысячи, а у муравья 6 тысяч глазков. Сколькими глазками на тебя смотрят вместе муха и муравей? (Напиши ответ не используя слово тысяч)', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Семена тыквы сохраняют всхожесть 8 лет, а пшеницы — на 8 лет больше. Сколько лет пшеница сохраняет всхожесть?', '16', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В Тихом океане 9 морей, а в Атлантическом — на 3 моря меньше. Сколько морей в Атлантическом океане?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В ларёк привезли 10 ящиков хурмы, а винограда — на 7 ящиков больше. Сколько ящиков винограда привезли в ларёк?', '17', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Длина синего отрезка 1 см, а зелёного — на 9 см больше. Какова длина зелёного отрезка?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В автобусе ехало 25 взрослых пассажиров, а детей — на 20 меньше. Сколько детей ехало в автобусе?', '5', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Из Нижнего Новгорода в Астрахань теплоход плывёт 5 суток, а обратно, против течения, — на 2 суток больше. Сколько суток плывёт теплоход из Астрахани в Нижний Новгород?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В Индийском океане 5 морей, а в Тихом — на 4 больше. Сколько морей в Тихом океане?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Теплоход от Херсона до Киева идёт 4 суток, а обратно — на 1 сутки меньше. Сколько суток идёт теплоход от Киева до Херсона?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Дикая утка от южного моря до северного моря летит 7 дней, а дикий гусь — на 2 дня дольше. Сколько времени летит дикий гусь?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У портнихи 15 катушек белых ниток, а чёрных катушек на 8 меньше. Сколько катушек чёрных ниток у портнихи?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В Северном Ледовитом океане 10 морей, а в Индийском — на 5 меньше. Сколько морей в Индийском океане?', '5', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Миши 20 наклеек, а у Игоря на 4 наклейки больше. Сколько наклеек у Игоря?', '24', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На одном этаже 9 жильцов, а на другом этаже на 2 жильца меньше. Сколько жильцов на другом этаже?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Антон нашёл 5 боровиков, а сыроежек — на 4 больше. Сколько сыроежек нашёл Антон?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('По течению катер проходит расстояние за 3 часа, а против течения — на 2 часа больше. Сколько времени катер плывёт против течения?', '5', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В детском саду 8 трёхколёсных велосипедов, а двухколёсных — на 2 меньше. Сколько двухколёсных велосипедов в детском саду?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Папа из 10 выстрелов попал 9 раз, а Олег — на 4 меньше. Сколько раз в мишень попал Олег?', '5', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Из 16 кг свежих груш сушёных можно получить на 12 кг меньше. Сколько килограммов сушёных груш можно получить?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Слон дышит с частотой 10 раз в минуту, а собака — на 15 раз больше. С какой частотой в минуту дышит собака?', '25', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Длина жёлтого отрезка 4 см, а красного — на 3 см больше. Какой длины красный отрезок?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Для варки варенья из вишни на 6 кг ягод берут сахарного песка на 2 кг меньше. Сколько потребуется сахарного песка?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В среду Митя выучил 2 стихотворения, в четверг — на 3 больше. Сколько стихотворений Митя выучил в четверг?', '5', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В первый день Маша прочитала 4 страницы, во второй — на 6 страниц больше. Сколько страниц она прочитала за второй день?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Васи 9 марок, а у Коли на 3 марки больше. Сколько марок у Коли?', '12', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У рака 10 ног, а у пчёлки — на 4 меньше. Сколько ног у пчёлки?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Кати 6 игрушек, а у Нади — на 4 больше. Сколько игрушек у Нади?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В первый день Миша нарисовал 5 рисунков, во второй — на 2 рисунка больше. Сколько рисунков нарисовал Миша за второй день?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В 1В классе 7 мальчиков, а в 1Б — на 3 больше. Сколько мальчиков в 1Б классе?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Папа зарабатывает 800 р., мама — на 400 меньше. Сколько зарабатывает мама?', '400', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В красном доме 15 жильцов, в зелёном — на 5 жильцов меньше. Сколько жильцов живёт в зелёном доме?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У сосны хвоинки живут 2 года, а у ели — на 10 лет больше. Сколько лет живут хвоинки у ели?', '12', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В русском языке 10 гласных букв (назови их устно), а звуков — на 4 меньше. Сколько гласных звуков в русском языке? (Назови их, устно)', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В русском языке 5 сонорных согласных (назови их устно), а парных согласных — на 7 больше. Сколько парных согласных в русском языке? (Назови их устно)', '12', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Длина огорода 6 м, а его ширина на 2 м меньше. Какова ширина огорода? (Начерти его на черновике)', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Ширина тесьмы 3 см, а ширина ленты на 7 см больше. Какова ширина ленты?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Пока хлеб был мягким, он весил 20 кг. Когда зачерствел, вес его сделался на 1 кг меньше. Каков вес чёрствого хлеба.', '19', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Длина синего отрезка 2 см, а красного — на 6 см больше. Какова длина красного отрезка?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У паука 8 ног, а у рака — на 2 больше. Сколько ног у рака?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У взрослого человека 5 л крови, а у ребёнка — на 2 л меньше. Сколько литров крови у ребёнка?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В первом классе 20 учеников, а во втором — на 5 человек больше. Сколько учеников во втором классе?', '25', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В первой группе детского сада 20 детей, во второй — на 5 детей меньше. Сколько детей во второй группе?', '15', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Длина синего отрезка 6 см, а красного — на 5 см больше. Чему равна длина красного отрезка?', '11', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В первом доме 90 окон, во втором — на 10 окон больше. Сколько окон во втором доме?', '100', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Семена гороха сохраняют жизнеспособность 30 лет, а семена лотоса — на 70 лет больше. Сколько лет сохраняют жизнеспособность семена лотоса?', '100', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В наше время размах крыльев у стрекоз 10 см, а в каменноугольный период размах крыльев у стрекоз был на 80 см больше. Чему был равен размах крыльев у стрекоз в каменноугольный период?', '90', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Пульс человека 60 ударов в минуту, а у лягушки — на 30 ударов в минуту меньше. Какой пульс у лягушки?', '30', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У слона пульс 20 ударов в минуту, а у паука — на 40 ударов в минуту больше. Какой пульс у паука?', '60', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У человека 500 мышц, а у саранчи — на 400 мышц больше. Сколько мышц у саранчи?', '900', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Продолжительность жизни мхов 10 лет, а ивы — на 90 лет больше. Сколько лет может прожить ива?', '100', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Продолжительность жизни драконова дерева 6 тысяч лет, а баобаба — на 1 тысячу лет меньше. Сколько лет живёт баобаб?', '5', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Синица за один день пролетает 100 км, а почтовый голубь — на 400 км больше. Сколько километров за день пролетает почтовый голубь?', '500', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('За два дня девочка прочитала 10 страниц. В первый день она прочитала 2 страницы. Сколько страниц она прочитала во второй день?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('За два дня турист прошёл 8 км. В первый день он прошёл 5 км. Сколько километров он прошёл во второй день?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Саша и Ваня поймали 10 карасей. Ваня поймал 4 карася. Сколько карасей поймал Саша?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На шашечной доске осталось 7 шашек, из них 5 белых. Сколько чёрных шашек на доске?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В наборе для труда 10 листов бумаги. Белой бумаги — 2 листа. Сколько листов цветной бумаги в наборе для труда?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В саду 6 кустов красной и чёрной смородины. Чёрной смородины 4 куста. Сколько кустов красной смородины в саду?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У кошки родилось 5 рыжих и белых котят. Рыжих — 2 котёнка. Сколько белых котят у кошки?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В классе 9 кассет. Из них 2 кассеты с песнями, а остальные — со сказками. Сколько кассет со сказками в классе?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В гирлянде 10 лампочек. Фиолетовых 6 лампочек, а остальные — зелёные. Сколько зелёных лампочек в гирлянде?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У наседки 8 цыплят. Из них 2 цыплёнка чёрных, а остальные — жёлтые. Сколько жёлтых цыплят у наседки?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Игоря и Жени 9 голубей. У Жени 7 голубей. Сколько голубей у Игоря?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На дереве сидело 7 птиц. Улетело 3 птицы. Сколько птиц осталось?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На столе стояло 9 чашек. Разбили 2 чашки. Сколько чашек осталось?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Кати было 7 гвоздик. Она подарила 3 гвоздики. Сколько гвоздик у неё осталось?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На кустике висело 6 ягод клубники. Созрели и упали 2 ягодки. Сколько ягод осталось?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Мама испекла 8 пирожков. Когда съели 5 пирожков, сколько пирожков осталось?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Ученику надо решить 10 задач. Он решил 4 задачи. Сколько задач ему осталось решить?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Ване подарили 8 книг. Он прочитал 6 книг. Сколько книг осталось прочитать Ване?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Коле подарили 10 наклеек. Он вклеил в альбом 3 наклейки. Сколько наклеек осталось вклеить?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В кроссворде 10 слов. Алла отгадала 8 слов. Сколько слов осталось отгадать девочке?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У врача 9 пациентов. Он посетил 6 пациентов. Сколько пациентов врачу осталось посетить?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Из сада принесли 16 стаканов малины и смородины. Малины принесли 7 стаканов. Сколько принесли смородины?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На полке стоит 15 книг. Из них 9 книг на английском языке, остальные — на немецком. Сколько книг на немецком языке стояло на полке?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Девочка за два дня прочитала 22 страницы. В первый день она прочитала 10 страниц. Сколько страниц прочитала девочка за второй день?', '12', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На шахматной доске стояло 15 фигур. Из них 7 чёрных. Сколько белых фигур на шахматной доске?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В вазе стояло 17 белых и красных роз. Красных было 5 роз. Сколько белых роз в вазе?', '12', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В магазин привезли 31 ящик со свёклой и морковью. Сколько привезли ящиков со свёклой, если с морковью привезли 22 ящика?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В двух кусках 30 м ситца. В первом куске 10 м. Сколько ситца во втором куске?', '20', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Для изготовления ёлочных украшений купили 45 листов цветной бумаги. Из них 19 листов зелёной бумаги, а остальные — жёлтые. Сколько жёлтой бумаги купили?', '26', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Для класса купили 9 мячей. Из них 6 больших, а остальные — маленькие. Сколько маленьких мячей купили для класса?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Ане подарили 8 воздушных шариков, красных и синих. Синих было 5 шариков. Сколько красных шариков подарили Ане?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Для детского сада сшили 18 игрушек. Сколько сшили зайцев, если было 8 мишек?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Во дворе играли 13 ребят. Из них 4 мальчика, а остальные — девочки. Сколько было девочек?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Заготовили 34 банки компота. Из них 12 банок вишнёвого компота, остальные — клубничного. Сколько банок клубничного компота заготовили?', '22', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В посёлке 24 дома. Сколько каменных домов, если деревянных 18 домов?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Юра решил 23 примера. Из них 11 примеров на сложение, а остальные — на вычитание. Сколько примеров на вычитание решил Юра?', '12', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В доме было 80 квартир. Из них 31 однокомнатная квартира, а остальные — двухкомнатные. Сколько двухкомнатных квартир в доме?', '49', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Во дворе стоят 12 автомашин. Сколько легковых автомашин стоит во дворе, если грузовых 4?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Мимо станции за день прошло 25 поездов. Сколько прошло товарных поездов, если пассажирских — 9 поездов?', '16', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В саду 17 кустов жёлтой и красной малины. Жёлтой малины 8 кустов. Сколько кустов красной малины росло в саду?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У лебедя на всём теле около 25 тысяч перьев. Из них на голове и шее 20 тысяч перьев. Сколько перьев на туловище лебедя?', '5', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На улице посадили 100 лип и клёнов. Клёнов было 30. Сколько посадили лип?', '70', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Мама заплатила за свёклу и капусту 100 р. Капуста стоила 40 р. Сколько стоит свёкла?', '60', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('3а две ручки папа заплатил 20 р. Одна ручка стоила 5 р. Сколько рублей стоила вторая ручка?', '15', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В течение жизни человек спит 25 лет. Из них 5 лет он видит сны. Сколько лет в течение жизни человек спит и не видит снов?', '20', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В русском языке всего 9 сонорных и всегда глухих согласных. Сонорных — 5 согласных. Сколько всегда глухих согласных?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В первый день портниха сшила 6 рубашек, во второй — еще несколько. Всего за два дня она сшила 10 рубашек. Сколько рубашек она сшила во второй день?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В вазе было 10 яблок. Съели 8 яблок. Сколько яблок осталось?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В пакете лежало 8 конфет. Съели 5 конфет. Сколько осталось?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Ребята сделали 10 скворечников. В школьном саду они повесили 8 скворечников. Сколько скворечников им осталось повесить?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В автобусе ехало 9 человек. На остановке вышли 5 человек. Сколько человек осталось в автобусе?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('С начала марта прошло 7 дней. Сколько дней осталось до конца марта? (В марте 31 день.)', '24', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Оля сделала 9 поздравительных открыток. Она подарила 8 открыток. Сколько открыток у неё осталось?', '1', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В коробке было 10 шоколадных конфет. Съели 7 конфет. Сколько конфет осталось?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Крышка стола имеет 3 угла. Один угол спилили. Сколько углов стало у крышки стола?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Ученику надо решить 8 примеров. Он решил 6 примеров. Сколько примеров ему осталось решить?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В книге 30 страниц. Катя прочитала 20 страниц. Сколько страниц осталось прочитать?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На проводах сидело 12 воробьёв и 5 синиц. Улетели все синицы и столько же воробьёв. Сколько воробьёв осталось?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В классе 13 комнатных растений. Дежурный полил 7 растений. Сколько растений осталось полить дежурному?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На клумбе росло 50 цветов. Сорвали 20 цветов. Сколько цветов осталось?', '30', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На дом было задано списать 23 слова. Маша списала 15 слов. Сколько слов осталось списать Маше?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Иры было 9 тетрадей. Когда несколько тетрадей Ира исписала, чистых осталось 6. Сколько тетрадей исписала Ира?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На тарелке было 10 персиков. Когда несколько персиков съели, на тарелке осталось 3 персика. Сколько персиков съели?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В магазине на полке стояло 8 кукол. После того как несколько кукол продали, на полке осталось 5 кукол. Сколько кукол продали?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Для ремонта купили 6 кусков обоев. Когда оклеили комнату, осталось 2 куска обоев. Сколько кусков обоев пошло на ремонт комнаты?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Для озеленения школьного участка купили 9 саженцев. После того как несколько саженцев посадили, осталось посадить 4 саженца. Сколько саженцев уже посадили на школьном участке?', '5', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У портнихи было 8 катушек ниток. Несколько катушек она истратила на пошив платьев. После этого у неё осталось 6 катушек. Сколько катушек ниток она истратила на пошив платьев?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В секции занималось 10 человек. Когда несколько человек заболело, на занятия пришло 7 человек. Сколько человек заболело?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На опушке играло 5 лисят. Когда несколько лисят убежало, осталось 2 лисёнка. Сколько лисят убежало?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Нелли было 7 открыток. После того как несколько открыток она подписала, у неё осталось 4 открытки. Сколько открыток Нелли подписала?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В парке было 9 скамеек. Когда несколько из них покрасили, то в парке осталось 7 некрашеных скамеек. Сколько скамеек покрасили?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На полке было 5 книг. Когда ещё несколько книг поставили на полку, их стало 8. Сколько книг поставили на полку?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В коробке было 3 карандаша. После того как в неё положили несколько карандашей, в коробке стало 10 карандашей. Сколько карандашей положили в коробку?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Серёжи было 4 марки. Ему подарили ещё несколько, и у мальчика стало 7 марок. Сколько марок подарили Серёже?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Светы в дневнике стояло 3 пятёрки. После того как она получила ещё несколько, их стало 5. Сколько пятёрок получила Света?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На стоянке было 7 машин. Когда несколько машин приехало, их стало 9. Сколько машин приехало?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Пети было 4 книги про животных. Когда ему подарили ещё несколько книг, их стало 8. Сколько книг подарили Пете?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В саду было 5 кустов облепихи. Когда посадили ещё несколько, то в саду стало 9 кустов облепихи. Сколько кустов посадили?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Было покрашено 6 стульев. Когда покрасили ещё несколько стульев, их стало 8. Сколько всего стульев покрасили?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Во дворе гуляли 10 ребят. Когда несколько человек ушли, их осталось 4. Сколько ребят ушло?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У кошки была 1 игрушка. После того как ей купили ещё несколько, их стало 5. Сколько игрушек купили для кошки?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В зоопарке было 2 зебры. Привезли ещё несколько зебр. Сколько зебр привезли, если их стало в зоопарке 7?', '5', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В кувшине было 12 стаканов молока. К обеду из кувшина взяли несколько стаканов. Сколько стаканов молока взяли к обеду, если в кувшине осталось 7 стаканов молока?', '5', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Серёжи было 6 яблок. Ему дали ещё несколько. После этого у него стало 10 яблок. Сколько яблок дали Серёже?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В вазе было 11 яблок. Когда несколько яблок съели, то осталось 6 яблок. Сколько яблок съели?', '5', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Вани было 2 солдатика. Когда мама купила ему ещё несколько, у него стало 6 солдатиков. Сколько солдатиков купила мама?', '4', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На полке стояло 27 книг. Сколько книг взяли с полки, если их осталось 20?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У Паши было 7 роботов. Когда мама купила ему ещё несколько, у него стало 9 роботов. Сколько роботов купила мама?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В классе 25 учеников. Несколько детей заболело, и в школу пришло 20 учеников. Сколько детей заболели?', '5', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В автобусе ехали 20 человек. Когда несколько человек вышли, осталось 15. Сколько человек вышли?', '5', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На кустике висело 8 ягод земляники. Когда несколько ягод созрело и упало, осталось 6 ягод. Сколько ягод созрело и упало?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На крыше сидело 7 голубей. Когда к ним прилетело ещё несколько, их стало 15. Сколько голубей прилетело?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Рыцарь, защищая прекрасную даму, сразился с 12-главым драконом. После того как дракон трусливо покинул поле битвы, рыцарю досталось в награду 5 голов дракона. Сколько голов унёс на своих плечах дракон, и как его теперь называют?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Школьный двор убирали 25 учеников. После того как несколько учеников ушли на урок, во дворе остались 12 учеников. Сколько учеников ушли на урок?', '13', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В спортивном зале занимались 16 человек. Когда несколько человек пришли, то стало 32 человека. Сколько человек пришли в спортивный зал?', '16', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Жена древнего охотника заготовила на зиму 12 мешков орехов. Зимой вся семья любила вечерами сидеть у костра и грызть орехи. К весне осталось всего 3 мешка. Сколько мешков орехов съела семья древнего охотника зимой?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В библиотеке класса было 49 книг. Когда ещё несколько книг ребята принесли из дома, то в библиотеке стало 63 книги. Сколько книг принесли ребята из дома?', '14', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Бабушка испекла 16 пирожков. После обеда их осталось 9. Сколько пирожков съели за обедом?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Почтальон должен разнести 24 журнала. Когда несколько журналов он разнёс, ему осталось разнести 4 журнала. Сколько журналов разнёс почтальон?', '20', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В бочке было 40 вёдер воды. Когда из неё вылили несколько вёдер, в ней осталось 30 вёдер. Сколько вёдер воды вылили из бочки?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На опушке леса мирно паслось 12 мамонтов. После набега древних охотников их осталось 10. Сколько мамонтов притащили охотники в свою доисторическую деревню?', '2', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На карусели катались 28 детей. Когда несколько детей сошли, на карусели осталось 20 детей. Сколько детей сошли с карусели?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В автобусе ехали 14 человек. На остановке в автобус вошли несколько человек, и в автобусе стало 32 человека. Сколько человек вошли в автобус?', '18', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Около школы росло 20 тополей. Сколько тополей посадили осенью, если стало 43 тополя?', '23', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На опушке леса играло 6 зайцев. Когда на эту опушку из леса выбежало ещё несколько зайцев, всего на опушке стало 11 зайцев. Сколько зайцев выбежало из леса?', '5', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Когда Валера раскрасил в книжке 4 картинки, ему осталось раскрасить 3. Сколько картинок в книжке?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Когда с ветки сорвали 6 яблок, то на ветке осталось 4 яблока. Сколько яблок было на ветке?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('После того как Денис решил 2 задачи, ему осталось решить 3. Сколько всего задач должен решить Денис?', '5', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Женя выучил 2 стихотворения, и ему осталось выучить ещё 1 стихотворение. Сколько всего стихотворений должен выучить Женя?', '3', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Мастер сделал 4 окна, ему осталось сделать ещё 5. Сколько всего окон должен сделать мастер?', '9', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Бабушка прополола 3 грядки, и ей осталось прополоть ещё 5 грядок. Сколько всего грядок надо было прополоть бабушке?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На сцену поставили 6 стульев, осталось поставить 2 стула. Сколько стульев должно стоять на сцене?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Вадик написал 5 словарных слов, ему осталось написать 3 слова. Сколько всего слов надо написать Вадику?', '8', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Когда с ветки упало 3 груши, их осталось столько же. Сколько груш было на ветке сначала?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Марина заточила 4 карандаша, и ей осталось заточить ещё 2. Сколько всего карандашей было у Марины?', '6', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('На стоянке было несколько машин. Когда 3 уехало, их осталось 4. Сколько машин было на стоянке сначала?', '7', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В вазе было несколько груш. Когда 2 груши съели, их осталось 8. Сколько груш было сначала?', '10', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('В классе учились ребята. Когда 10 ребят заболели, их осталось 20. Сколько всего ребят учились в классе?', '30', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('Мама дала Диме деньги на покупку тетрадей. Когда он истратил 15 р., у него осталось 10 р. Сколько денег ему дали?', '25', false);
INSERT INTO public.tasks (condition, answer, status) VALUES ('У продавщицы были розы. Когда она продала 7 роз, у неё их осталось 5. Сколько роз было у продавщицы сначала?', '12', false);
