create table tasks
(
    id        int GENERATED BY DEFAULT AS IDENTITY primary key,
    condition varchar not null,
    answer    varchar (50) not null,
    status    boolean default false not null
);

comment on table tasks is 'Задачи по математике';

comment on column tasks.id is 'Номер задачи';

comment on column tasks.condition is 'Условие задачи';

comment on column tasks.answer is 'Ответ на задачу';

comment on column tasks.status is 'Статут задачи';

alter table tasks
    owner to postgres;


