INSERT INTO public.tasks (number, condition, answer, status) VALUES (1, 'На ветке сидело 4 воробья и 3 снегиря. Сколько птиц сидело на ветке?', '7', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (3, 'На лугу паслось 5 коров и 1 бык. Сколько животных было на лугу?', '6', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (4, 'На стоянке стояло 3 машины. Вечером приехало ещё 6 машин. Сколько машин стало?', '9', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (5, 'На кусте было 2 распустившиеся розы. Через 3 дня распустилось ещё 4 розы. Сколько распустившихся роз стало на кусте?', '6', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (6, 'На столе стояло 4 тарелки. Мама поставила ещё 2 тарелки. Сколько тарелок стало на столе?', '6', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (7, 'У подъезда росло 4 дерева. Дети посадили столько же деревьев. Сколько деревьев теперь растёт у подъезда?', '8', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (8, 'У Кати было 4 куклы. На день рождения девочке подарили ещё 3 куклы. Сколько кукол стало у Кати?', '7', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (9, 'В маршрутном такси ехало 5 человек. На остановке вошли ещё 3 человека. Сколько пассажиров стало в маршрутном такси?', '8', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (10, 'У мамы было 9 гвоздик. Потом ей подарили ещё 3 гвоздики. Сколько гвоздик стало у мамы?', '12', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (11, 'У Вани было 2 кассеты с мультфильмами. Ему купили ещё 4 кассеты. Сколько кассет стало у Вани?', '6', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (12, 'На даче росло 4 куста смородины. Посадили ещё 6 кустов. Сколько кустов смородины теперь растёт на даче?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (13, 'У Светы было 5 открыток. Ей прислали ещё 4 открытки. Сколько открыток стало у Светы?', '9', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (14, 'Мальчик за первую четверть прочитал 4 книги, за вторую четверть — 5 книг, а за третью столько, сколько за первую и вторую четверти вместе. Сколько книг прочитал мальчик в третьей четверти?', '9', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (15, 'В букете было 2 красные розы, 5 белых роз, а розовых столько, сколько красных и белых вместе. Сколько розовых роз в букете?', '7', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (16, 'В хоре поют 3 девочки, танцами занимаются 5 девочек, а в театральном кружке играют столько девочек, сколько их поёт в хоре и занимается танцами. Сколько девочек в театральном кружке?', '8', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (17, 'На день рождения Маше подарили 3 куклы, 5 мишек, а воздушных шариков столько, сколько кукол и мишек вместе. Сколько воздушных шариков подарили Маше?', '8', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (18, 'На опушке леса росло 4 берёзы и 3 дуба, а елей столько, сколько берёз и дубов вместе. Сколько елей росло на опушке леса?', '7', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (19, 'Саша исписал за первую четверть 2 тетради, за вторую четверть — 4 тетради, а за третью четверть столько, сколько за первую и вторую четверти вместе. Сколько тетрадей исписал Саша в третей четверти?', '6', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (20, 'В букете 3 колокольчика, 7 ромашек, а васильков столько, сколько колокольчиков и ромашек вместе. Сколько васильков в букете?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (21, 'На стоянке стояло 4 красные машины, 5 синих, а белых машин столько, сколько красных и синих вместе. Сколько белых машин на стоянке?', '9', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (22, 'Миша утром решил 1 задачу, днём — 4 задачи, а вечером столько, сколько утром и днём вместе. Сколько задач решил Миша вечером?', '5', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (23, 'В русском языке 3 согласные буквы, которые обозначают всегда твёрдый звук, и 3 согласные буквы, которые обозначают всегда мягкий звук, а звонких парных согласных столько, сколько всегда твёрдых и всегда мягких вместе. Сколько в русском языке звонких парных согласных букв?', '6', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (24, 'Оле 5 лет, Тане 3 года, а Юре столько лет, сколько Оле и Тане вместе. Сколько лет Юре?', '8', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (25, 'В первый день Митя нарисовал 4 рисунка, во второй — столько же. Сколько всего рисунков нарисовал Митя?', '8', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (26, 'У Юры 3 машинки и у Максима столько же. Сколько машинок у Максима?', '3', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (27, 'В одном стручке 5 горошин и в другом столько же. Сколько горошин в двух стручках?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (28, 'На одной ветке 2 яблока и на другой столько же. Сколько яблок на двух ветках?', '4', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (29, 'У папы 1 сестра и столько же братьев. Сколько всего братьев и сестёр у папы?', '2', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (30, 'В вазе лежало 5 карамелек и столько же шоколадных конфет. Сколько всего конфет лежало в вазе?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (31, 'У кошки 3 белых и столько же чёрных котят. Сколько всего котят у кошки?', '6', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (32, 'На доске лежало 4 куска белого мела и столько же зелёного. Сколько всего кусков мела лежало на доске?', '8', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (33, 'На столе стояло 2 блюдца и столько же чашек. Сколько посуды на столе?', '4', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (34, 'В секции занимались 5 мальчиков и столько же девочек. Сколько детей занималось в секции?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (35, 'На берёзе сидело 6 воробьёв. Прилетело ещё 4. Сколько воробьёв стало?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (36, 'Белка устроила гнездо в дупле дуба. Днём она принесла туда 8 грибов, а вечером — 4 гриба. Сколько грибов оказалось в дупле?', '12', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (37, 'На цветке сидит пчела, собирает пыльцу. К ней прилетела ещё 1 пчела. Сколько всего пчёл на цветке?', '2', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (38, 'Ребята заготовили для птиц 5 кг рябины и 5 кг семян арбуза. Сколько всего килограммов семян заготовили ребята?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (39, 'Вокруг Марса вращаются 2 естественных спутника, а вокруг планеты Уран — 5 спутников. Сколько всего спутников у Марса и Урана вместе?', '7', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (40, 'Геологи нашли семь камней, масса которых 1 кг, 2 кг, 3 кг, 4 кг, 5 кг, 6 кг, 7 кг. Эти камни разложили в четыре рюкзака так, чтобы в каждом рюкзаке масса камней была одинакова. Как это сделали? (Напиши сколько камней в каждом рюкзаке)', '7', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (41, 'В хоре пели 4 мальчика и 6 девочек. Сколько детей всего пело в хоре?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (42, 'Дети учатся в школе 4 месяца до Нового года и 5 месяцев после Нового года. Сколько всего месяцев дети учатся в школе?', '9', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (43, 'На стройку привезли 5 машин песка и 3 машины цемента. Сколько всего машин приехало на стройку?', '8', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (44, 'В первом конверте 5 марок, а во втором — 3 марки. Сколько всего марок в двух конвертах?', '8', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (45, 'Мальчик за первую четверть исписал 6 тетрадей, за вторую четверть — 3 тетради. Сколько всего тетрадей он исписал за две четверти?', '9', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (46, 'В коридоре стояло 5 стульев. Принесли ещё 3. Сколько стульев стало?', '8', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (47, 'В первый день машина проехала 30 км, во второй — 10 км. Сколько километров машина проехала за два дня?', '40', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (48, 'Во дворе играло 5 котят. К ним подошло ещё 3 котёнка. Сколько котят стало?', '8', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (49, 'В первую четверть Аня болела 4 дня, во вторую — 6 дней. Сколько всего дней Аня болела в эти две четверти?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (50, 'В автобусе ехали 7 пассажиров. На остановке вошли ещё 3 пассажира. Сколько пассажиров стало в автобусе?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (51, 'В первый день около школы посадили 20 деревьев, во второй — ещё 10 деревьев. Сколько всего деревьев посадили?', '30', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (52, 'В первой группе 7 мальчиков, во второй группе 3 мальчика, а в третьей столько, сколько в первой и второй вместе. Сколько мальчиков в третьей группе?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (53, 'Таня засушила 4 кленовых и 5 дубовых листьев. Сколько всего листьев засушила Таня?', '9', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (54, 'В первый день в магазин привезли 5 пачек книг, во второй — 4 пачки, а в третий столько, сколько в первый и второй вместе. Сколько пачек книг привезли в магазин в третий день?', '9', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (55, 'Зина купила 5 тетрадей в клетку и 2 в линейку. Сколько всего тетрадей купила Зина?', '7', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (56, 'За последние три столетия исчезло 36 видов млекопитающих и 94 вида птиц. Скольких всего видов птиц и млекопитающих лишилась наша родная планета?', '130', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (57, 'Возле школы росло 9 елей. Посадили ещё 4 дуба и 6 елей. Сколько всего елей стало возле школы?', '15', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (58, 'Дикие гуси живут 80 лет, а собаки — 20 лет. Орёл живёт столько, сколько собака и гусь вместе взятые. Сколько лет живёт орёл?', '100', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (59, 'Сейчас охота в нашей стране запрещена полностью на 18 видов зверей и 29 видов птиц. На сколько видов зверей и птиц запрещена охота?', '47', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (60, 'Таня вымыла 6 тарелок, а Коля вымыл 7 тарелок. Сколько всего тарелок вымыли дети?', '13', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (61, 'В первой квартире живут 3 человека, во второй — 4 человека, а в третьей столько, сколько в первой и второй вместе. Сколько человек живёт в третьей квартире?', '7', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (62, 'Глаз насекомого имеет мозаичное (фасеточное) строение. Он состоит из множества глазков. У мухи их 4 тысячи, а у муравья 6 тысяч глазков. Сколькими глазками на тебя смотрят вместе муха и муравей? (Напиши ответ не используя слово тысяч)', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (63, 'Семена тыквы сохраняют всхожесть 8 лет, а пшеницы — на 8 лет больше. Сколько лет пшеница сохраняет всхожесть?', '16', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (64, 'В Тихом океане 9 морей, а в Атлантическом — на 3 моря меньше. Сколько морей в Атлантическом океане?', '6', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (65, 'В ларёк привезли 10 ящиков хурмы, а винограда — на 7 ящиков больше. Сколько ящиков винограда привезли в ларёк?', '17', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (66, 'Длина синего отрезка 1 см, а зелёного — на 9 см больше. Какова длина зелёного отрезка?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (67, 'В автобусе ехало 25 взрослых пассажиров, а детей — на 20 меньше. Сколько детей ехало в автобусе?', '5', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (68, 'Из Нижнего Новгорода в Астрахань теплоход плывёт 5 суток, а обратно, против течения, — на 2 суток больше. Сколько суток плывёт теплоход из Астрахани в Нижний Новгород?', '7', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (69, 'В Индийском океане 5 морей, а в Тихом — на 4 больше. Сколько морей в Тихом океане?', '9', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (70, 'Теплоход от Херсона до Киева идёт 4 суток, а обратно — на 1 сутки меньше. Сколько суток идёт теплоход от Киева до Херсона?', '3', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (71, 'Дикая утка от южного моря до северного моря летит 7 дней, а дикий гусь — на 2 дня дольше. Сколько времени летит дикий гусь?', '9', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (73, 'У портнихи 15 катушек белых ниток, а чёрных катушек на 8 меньше. Сколько катушек чёрных ниток у портнихи?', '7', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (74, 'В Северном Ледовитом океане 10 морей, а в Индийском — на 5 меньше. Сколько морей в Индийском океане?', '5', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (75, 'У Миши 20 наклеек, а у Игоря на 4 наклейки больше. Сколько наклеек у Игоря?', '24', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (76, 'На одном этаже 9 жильцов, а на другом этаже на 2 жильца меньше. Сколько жильцов на другом этаже?', '7', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (77, 'Антон нашёл 5 боровиков, а сыроежек — на 4 больше. Сколько сыроежек нашёл Антон?', '9', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (78, 'По течению катер проходит расстояние за 3 часа, а против течения — на 2 часа больше. Сколько времени катер плывёт против течения?', '5', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (79, 'В детском саду 8 трёхколёсных велосипедов, а двухколёсных — на 2 меньше. Сколько двухколёсных велосипедов в детском саду?', '6', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (80, 'Папа из 10 выстрелов попал 9 раз, а Олег — на 4 меньше. Сколько раз в мишень попал Олег?', '5', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (81, 'Из 16 кг свежих груш сушёных можно получить на 12 кг меньше. Сколько килограммов сушёных груш можно получить?', '4', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (82, 'Слон дышит с частотой 10 раз в минуту, а собака — на 15 раз больше. С какой частотой в минуту дышит собака?', '25', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (83, 'Длина жёлтого отрезка 4 см, а красного — на 3 см больше. Какой длины красный отрезок?', '7', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (84, 'Для варки варенья из вишни на 6 кг ягод берут сахарного песка на 2 кг меньше. Сколько потребуется сахарного песка?', '4', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (85, 'В среду Митя выучил 2 стихотворения, в четверг — на 3 больше. Сколько стихотворений Митя выучил в четверг?', '5', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (86, 'В первый день Маша прочитала 4 страницы, во второй — на 6 страниц больше. Сколько страниц она прочитала за второй день?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (87, 'У Васи 9 марок, а у Коли на 3 марки больше. Сколько марок у Коли?', '12', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (88, 'У рака 10 ног, а у пчёлки — на 4 меньше. Сколько ног у пчёлки?', '6', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (89, 'У Кати 6 игрушек, а у Нади — на 4 больше. Сколько игрушек у Нади?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (90, 'В первый день Миша нарисовал 5 рисунков, во второй — на 2 рисунка больше. Сколько рисунков нарисовал Миша за второй день?', '7', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (91, 'В 1В классе 7 мальчиков, а в 1Б — на 3 больше. Сколько мальчиков в 1Б классе?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (92, 'Папа зарабатывает 800 р., мама — на 400 меньше. Сколько зарабатывает мама?', '400', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (93, 'В красном доме 15 жильцов, в зелёном — на 5 жильцов меньше. Сколько жильцов живёт в зелёном доме?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (94, 'У сосны хвоинки живут 2 года, а у ели — на 10 лет больше. Сколько лет живут хвоинки у ели?', '12', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (95, 'В русском языке 10 гласных букв (назови их устно), а звуков — на 4 меньше. Сколько гласных звуков в русском языке? (Назови их, устно)', '6', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (96, 'В русском языке 5 сонорных согласных (назови их устно), а парных согласных — на 7 больше. Сколько парных согласных в русском языке? (Назови их устно)', '12', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (97, 'Длина огорода 6 м, а его ширина на 2 м меньше. Какова ширина огорода? (Начерти его на черновике)', '4', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (98, 'Ширина тесьмы 3 см, а ширина ленты на 7 см больше. Какова ширина ленты?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (99, 'Пока хлеб был мягким, он весил 20 кг. Когда зачерствел, вес его сделался на 1 кг меньше. Каков вес чёрствого хлеба.', '19', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (100, 'Длина синего отрезка 2 см, а красного — на 6 см больше. Какова длина красного отрезка?', '8', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (101, 'У паука 8 ног, а у рака — на 2 больше. Сколько ног у рака?', '10', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (102, 'У взрослого человека 5 л крови, а у ребёнка — на 2 л меньше. Сколько литров крови у ребёнка?', '3', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (103, 'В первом классе 20 учеников, а во втором — на 5 человек больше. Сколько учеников во втором классе?', '25', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (104, 'В первой группе детского сада 20 детей, во второй — на 5 детей меньше. Сколько детей во второй группе?', '15', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (105, 'Длина синего отрезка 6 см, а красного — на 5 см больше. Чему равна длина красного отрезка?', '11', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (106, 'В первом доме 90 окон, во втором — на 10 окон больше. Сколько окон во втором доме?', '100', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (107, 'Семена гороха сохраняют жизнеспособность 30 лет, а семена лотоса — на 70 лет больше. Сколько лет сохраняют жизнеспособность семена лотоса?', '100', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (108, 'В наше время размах крыльев у стрекоз 10 см, а в каменноугольный период размах крыльев у стрекоз был на 80 см больше. Чему был равен размах крыльев у стрекоз в каменноугольный период?', '90', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (109, 'Пульс человека 60 ударов в минуту, а у лягушки — на 30 ударов в минуту меньше. Какой пульс у лягушки?', '30', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (110, 'У слона пульс 20 ударов в минуту, а у паука — на 40 ударов в минуту больше. Какой пульс у паука?', '60', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (111, 'У человека 500 мышц, а у саранчи — на 400 мышц больше. Сколько мышц у саранчи?', '900', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (112, 'Продолжительность жизни мхов 10 лет, а ивы — на 90 лет больше. Сколько лет может прожить ива?', '100', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (113, 'Продолжительность жизни драконова дерева 6 тысяч лет, а баобаба — на 1 тысячу лет меньше. Сколько лет живёт баобаб?', '5', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (114, 'Синица за один день пролетает 100 км, а почтовый голубь — на 400 км больше. Сколько километров за день пролетает почтовый голубь?', '500', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (115, 'За два дня девочка прочитала 10 страниц. В первый день она прочитала 2 страницы. Сколько страниц она прочитала во второй день?', '8', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (116, 'За два дня турист прошёл 8 км. В первый день он прошёл 5 км. Сколько километров он прошёл во второй день?', '3', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (117, 'Саша и Ваня поймали 10 карасей. Ваня поймал 4 карася. Сколько карасей поймал Саша?', '6', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (118, 'На шашечной доске осталось 7 шашек, из них 5 белых. Сколько чёрных шашек на доске?', '2', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (119, 'В наборе для труда 10 листов бумаги. Белой бумаги — 2 листа. Сколько листов цветной бумаги в наборе для труда?', '8', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (120, 'В саду 6 кустов красной и чёрной смородины. Чёрной смородины 4 куста. Сколько кустов красной смородины в саду?', '2', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (121, 'У кошки родилось 5 рыжих и белых котят. Рыжих — 2 котёнка. Сколько белых котят у кошки?', '3', false);
INSERT INTO public.tasks (number, condition, answer, status) VALUES (122, 'В классе 9 кассет. Из них 2 кассеты с песнями, а остальные — со сказками. Сколько кассет со сказками в классе?', '7', false);
